name: Security Scans

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
  SRCCLR_REGION: ${{ vars.SRCCLR_REGION }}
  VERACODE_API_KEY_ID: ${{secrets.VERACODE_API_ID}}
  VERACODE_API_KEY_SECRET: ${{secrets.VERACODE_API_KEY}}
  OVER_LIMIT_DEFAULT: true

jobs:
  build:
    runs-on: ${{ github.event.inputs.Runner-Image }}
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: write
      packages: write
    
    
    steps:

      - name: check env
        run: |
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces it and clones the repo
      - uses: actions/checkout@v4.2.2

      # Need to run a step here that checks for the package managers needed in the file system and then installs them appropirately
      # Later itteration need to do this with an image

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install the Veracode CLI 
        run: |
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            ./veracode --help
            ls
            mkdir .veracode 
            mkdir .veracode/build/ 
            ./veracode package -a -d -s ./Scripts -o .veracode/build/
            ls
            ls .veracode/build/

      - name: Veracode Dependency Scanning
        continue-on-error: true
        if: ${{ inputs.Run-SCA-Agent-Based-Scan == 'true' }}
        env:
          SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-sca@6f565b462af9b5e74d2dbbdddcb5cacd7bc7fe4f
        uses: veracode/veracode-sca@v2.1.11
        with:
          # Authorization token to query and create issues
          github_token: ${{ github.token }}
          # Run the SRCCLR with the `--quick` options
          quick: false # optional, default is false
          # Show update advisor
          update_advisor: true # optional, default is false
          # A git URL to work with in case the scan is not for the current repository
          #url: # optional, default is 
          # An attribute to instruct the action to create an issue from found vulnerability or just simple text output
          create-issues: true # optional, default is false
          # A path within the repository where the build definition starts
          path: ./Scripts # optional, default is .
          # Run the SRCCLR in debug mode
          debug: true # optional, default is false
          # Run the SRCCLR with the `--skip-collectors` options
          #skip-collectors: # optional, default is false
          # Run the SRCCLR with the `--allow-dirty` option
          allow-dirty: true # optional, default is false
          # Run the SRCCLR with the `--recursive` option
          recursive: true # optional, default is false
          # Run the SRCCLR with the `--skip-vms` option
          #skip-vms: # optional, default is false
          # Run the SRCCLR with the `--no-graphs` option
          #no-graphs: # optional, default is false
                

          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
            # Artifact name
            name: veracode-build-artifact
            # optional, default is artifact
            # A file, directory or wildcard pattern that describes what to upload
            path: .veracode/build/
            # The desired behavior if no files are found using the provided path.
            if-no-files-found: warn
        
  veracode-sast-analysis:
    # Requires the previous step to be completed prior to moving onto this step, otherwise can be set to run in parallel
    needs: build
    runs-on: '${{ github.event.inputs.Runner-Image }}'
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          repository: ${{ inputs.RepoUrl }}
           
      - uses: actions/download-artifact@v4.1.8
        continue-on-error: true
        with: 
            name: veracode-build-artifact
            path: .veracode/build/
            merge-multiple: true
            repository: ${{inputs.RepoUrl}}
            
            
      - run: pwd && ls
      - run: |
          ls -la
          ls -la .veracode/build/
          fileLocation=".veracode/build/" # places the built artifacts in the veracode build folder 
          file_array=($(ls $fileLocation ))
          for file in "${file_array[@]}"; do
              echo "Processing file: $file"
                  
             
              if [[ -z "$fileLocation/$file" ]]; then
                  echo "No File has been passed/unsupported file"
              fi
              
              if [[ "$file" =~ \.(war|ear|jar|zip)$ ]]; then
                      allowed_files+=("$file")  
              else
                      excluded_files+=("$file")  
              fi
              echo $(stat --format=%s $fileLocation/$file)
              
          done
          if [[ $(stat --format=%s $fileLocation) -le 20000 ]]; then
              echo "OVER_LIMIT=false" >> $GITHUB_ENV
          else
              echo "OVER_LIMIT=${{env.OVER_LIMIT_DEFAULT}}" >> $GITHUB_ENV
          fi
      # Downloads the pipeline scanner jar directly for each of the operating systems and settings defined
      
          
      - name: Veracode Pipeline-Scan
        continue-on-error: true
      # You may pin to the exact commit or the version.
      # uses: veracode/Veracode-pipeline-scan-action@7bbcef3efc8720d36302fc912a7d63f7aba34f76
        uses: veracode/Veracode-pipeline-scan-action@v1.0.14
        with:
            # vid
            vid: ${{secrets.VERACODE_API_ID}}
            # vkey
            vkey: ${{secrets.VERACODE_API_KEY}}
            # Filename of the packaged application to upload and scan.
            file: .veracode/build/*.zip
            # GITHUB_TOKEN or a repo scoped PAT.
            token: ${{ secrets.GH_TOKEN }} # default is ${{ github.token }}
            # Name of the security policy to download as a file. Required only if you want to download the configuration for a custom policy defined by your organization. After downloading the policy, you can provide this file in a subsequent command using the policy_file parameter.
            #request_policy: # optional
            # Fail the pipeline job if the scan finds flaws of the specified severities. Enter a comma-separated list of severities in quotation marks.
            #fail_on_severity: # optional
            # Fail the pipeline job if the scan finds flaws of the specified CWEs. Enter a comma-separated list of CWE IDs.
            #fail_on_cwe: # optional
            # Filter the flaws that exist in the specified baseline file and show only the additional flaws in the current scan.
            #baseline_file: # optional
            # Name of the Veracode default policy rule to apply to the scan results. You can only use this parameter with a Veracode default policy.
            #policy_name: # optional
            # Name of the local policy file you want to apply to the scan results. To download this file, use the --request_policy parameter.
            #policy_file: # optional
            # Amount of time, in minutes, for the Pipeline Scan to wait before reporting an unsuccessful scan if the scan does not complete. Default is 60 minutes, which is also the maximum value.
            #timeout: # optional
            # Enter true to show detailed messages for each issue in the results summary.
            #issue_details: # optional
            # Enter true to show a human-readable results summary on the console. Default is true.
            #summary_display: # optional
            # Enter true to show the JSON containing the scan results on the console. Default is false.
            #json_display: # optional
            # Enter true to display detailed messages in the scan results. Default is false.
            #verbose: # optional
            # Enter true to save the scan results as a human-readable file. Default is false.
            #summary_output: # optional
            # Enter the filename of the scan results summary file. The file is stored in the current directory. Default is results.txt.
            #summary_output_file: # optional
            # Enter true to save the scan results in JSON format. Default is true.
            #json_output: # optional
            # Rename the JSON file that contains the scan results. The file is stored in the current directory. Default filename is results.json.
            #json_output_file: # optional
            # Enter the filename in the current directory to save results that violate pass-fail criteria. Default is filtered_results.json.
            #filtered_json_output_file: # optional
            # Enter the name of the CI/CD code repository that runs a Pipeline Scan. This parameter adds the repository name to the scan results, which can help you track scans across repositories.
            #project_name: # optional
            # Enter the source control URL for the CI/CD code repository that runs a Pipeline Scan.
            #project_url: # optional
            # Enter the source control reference, revision, or branch for the CI/CD code repository that runs a Pipeline Scan.
            #project_ref: # optional
            # Enter the [application profile](https://docs.veracode.com/r/request_profile) ID for the application you want to upload and scan.
            #app_id: # optional
            # Enter one these values, which are case-sensitive, for the type of development stage: Development, Testing, Release.
            #development_stage: # optional
            # Enable debug mode. 1 for on
            #debug: # optional
            # Enable the storage of a baseline file. Takes true or fales
            #store_baseline_file: # optional
            # Enter the branch name where the baseline file should be stored
            #store_baseline_file_branch: # optional
            # From which results should the baseline file be created. standard = full results || filtered = filtered results
            #create_baseline_from: # optional
            # Fail the build upon findings. Takes true or false
            # fail_build: # optional
            # Enter a case-sensitive, comma-separated list of name patterns that represent the names of the modules to scan as top-level modules. Veracode identifies these modules during prescan. The * wildcard matches zero or more characters. The ? wildcard matches exactly one character. For example, to include various module names that contain module: --include "module 1, module-*, module2.jar". The scan results show the names of the modules that Veracode identified and the modules included in the scan. This parameter does not pause, stop, or impact the performance of your pipeline.
            # include: # optional
  
   name: Veracode Upload And Scan
        continue-on-error: true
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-uploadandscan-action@35794dab9fbcd28fac19e44963f80646b27f4a7f
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
          # appname
          appname: 'Veracode-scripts'
          # createprofile
          createprofile: true # default is true
          # filepath
          filepath: .veracode/build/
          # version
          version:  ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} # default is Scan from Github job: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          # vid
          vid: ${{secrets.VERACODE_API_ID}}
          # vkey
          vkey: ${{secrets.VERACODE_API_KEY}}
          # true or false
          #createsandbox: false # optional
          # name of the sandbox
          #sandboxname: # optional
          # wait X minutes for the scan to complete
          #scantimeout: # optional
          # modules to exclude from module selection
          #exclude: # optional
          # modules to include in module selection
          #include: # optional
          # business criticality - policy selection
          #criticality: # optional
          # filename pattern
          #pattern: # optional
          # replacement
          #replacement: # optional
          # specify to scan in a sandbox
          #sandboxid: # optional
          # All top level modules
          #scanallnonfataltoplevelmodules: # optional
          # platform selected modules
          #selected: # optional
          # selected modules like from previous scan
          #selectedpreviously: # optional
          # teams
          #teams: # optional
          # teams
          #toplevel: # optional
          # automatically delete the current scan if there are any errors when uploading files or starting the scan
          deleteincompletescan: 2 # optional
          # specify version of the Java API Wrapper; default is latest
          #javawrapperversion: # optional
          # show detailed diagnostic information, which you can use for debugging, in the output.
          debug: 1 # optional

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
        # Artifact name
          name: veracode-results # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: "**results.json"

  get-policy-flaws:
    needs: veracode-sast-analysis
    runs-on: ${{ github.event.inputs.Runner-Image }}
    container: 
     image: veracode/api-signing:latest
    steps:
         - name: get policy flaws
           run: |
             cd /tmp
             export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
             export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
             guid=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?name=Veracode-scripts" | jq -r '._embedded.applications[0].guid') 
             echo GUID: ${guid}
             total_flaws=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True" | jq -r '.page.total_elements')
             echo TOTAL_FLAWS: ${total_flaws}
             http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True&size=${total_flaws}" > policy_flaws.json
  
         - name: save results file
           uses: actions/upload-artifact@v3
           with:
             name: policy-flaws
             path: /tmp/policy_flaws.json
  
         - name: Convert policy scan output to SARIF format
           id: convert-policy
           #if: ${{ github.event.inputs.Run-Upload-and-Scan }}
           uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.4
           with:
            results-json: /tmp/policy_flaws.json
            output-results-sarif: veracode-results.sarif
            repo_owner: ${{ github.repository.owner }}
            repo_name: ${{ github.repository.name }}
            commitSHA: ${{ github.sha }}
            ref: ${{ github.ref }}
            githubToken: ${ github.token }
            
  get-pipeline-results:
    needs: veracode-sast-analysis
    runs-on: ${{ github.event.inputs.Runner-Image }}
    steps:
      - name: get pipeline results
        uses: actions/download-artifact@v3
          #with:
          #  name: "Veracode Pipeline-Scan Results"
            
      - name: Convert pipeline scan output to SARIF format
        if: ${{ github.event.inputs.Run-Pipeline-Scan }}
        id: convert-pipeline
        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.4
        with:
            results-json: filtered_results.json
            output-results-sarif: veracode-results.sarif
            repo_owner: ${{ github.repository.owner }}
            repo_name: ${{ github.repository.name }}
            commitSHA: ${{ github.sha }}
            ref: ${{ github.ref }}
            githubToken: ${ github.token }
  

   
